ELibrary.Web/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ELibrary.Domain.Models;
using ELibrary.Repository;
using Microsoft.AspNetCore.Authorization;
using ELibrary.Service.Interface;
using ELibrary.Service.RDF.Interface;
using ELibrary.Service.RDF.Extension;

namespace ELibrary.Web.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly IAuthorService _authorService;
        private readonly IRDFService _rdfService;
        public AuthorsController(ApplicationDbContext context, IAuthorService authorService, IRDFService rdfService)
        {
            _authorService = authorService;
            _rdfService = rdfService;
        }

        // GET: Authors
        public IActionResult Index()
        {
            return View(_authorService.GetAll());
        }

        // GET: Authors/Details/5
        public IActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = _authorService.Get(id);
            if (author == null)
            {
                return NotFound();
            }

            if (Request.Headers.ContainsKey("Accept"))
            {
                if (Request.Headers["Accept"] == "text/turtle")
                {
                    Response.Headers.Add("Content-Type", "text/turtle");
                    return File(author.GetRDFGraph(Service.RDF.Enum.Syntax.Turtle), "text/turtle");
                }
                if (Request.Headers["Accept"] == "application/rdf+xml")
                {
                    Response.Headers.Add("Content-Type", "application/rdf+xml");
                    return File(author.GetRDFGraph(Service.RDF.Enum.Syntax.RDFXML), "application/rdf+xml");
                }
            }

            return View(author);
        }

        // GET: Authors/MoreDetails/5
        public IActionResult MoreDetails(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = _authorService.Get(id);
            if (author == null)
            {
                return NotFound();
            }

            var info = _rdfService.GetAuthorInfo(author.FullName());

            if (Request.Headers.ContainsKey("Accept"))
            {
                if (Request.Headers["Accept"] == "text/turtle")
                {
                    Response.Headers.Add("Content-Type", "text/turtle");
                    return File(info.AsGraph(author, Service.RDF.Enum.Syntax.Turtle), "text/turtle");
                }
                if (Request.Headers["Accept"] == "application/rdf+xml")
                {
                    Response.Headers.Add("Content-Type", "application/rdf+xml");
                    return File(info.AsGraph(author, Service.RDF.Enum.Syntax.RDFXML), "application/rdf+xml");
                }
            }

            string subject = info[0].Value("author").ToString();

            IDictionary<string, List<VDS.RDF.INode>> props = new Dictionary<string, List<VDS.RDF.INode>>();
            foreach(var i in info)
            {
                string key = i.Value("rel").ToString();
                if (!props.ContainsKey(key))
                    props.Add(new KeyValuePair<string, List<VDS.RDF.INode>>(key, new List<VDS.RDF.INode>()));
                props[key].Add(i.Value("obj"));
            }

            ViewData["subject"] = subject;
            ViewData["authorId"] = author.Id;
            return View(props);
        }

        // GET: Authors/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Create([Bind("Name,Surname,Country,Image,Id")] Author author)
        {
            if (ModelState.IsValid)
            {
                author.Id = Guid.NewGuid();
                _authorService.Insert(author);
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Edit/5
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = _authorService.Get(id);
            if (author == null)
            {
                return NotFound();
            }
            return View(author);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(Guid id, [Bind("Name,Surname,Country,Image,Id")] Author author)
        {
            if (id != author.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _authorService.Update(author);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AuthorExists(author.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Delete/5
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(Guid? id)
        {
            // cannot delete author if he has books

            if (id == null)
            {
                return NotFound();
            }

            var author = _authorService.Get(id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult DeleteConfirmed(Guid id)
        {
            var author = _authorService.Get(id);
            _authorService.Delete(author);
            return RedirectToAction(nameof(Index));
        }

        private bool AuthorExists(Guid id)
        {
            return _authorService.Get(id) != null;
        }
    }
}

ELibrary.Web/Controllers/PublishersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ELibrary.Domain.Models;
using ELibrary.Repository;
using ELibrary.Service.Interface;
using Microsoft.AspNetCore.Authorization;

namespace ELibrary.Web.Controllers
{
    public class PublishersController : Controller
    {
        private readonly IPublisherService _publisherService;

        public PublishersController(IPublisherService publisherService)
        {
            _publisherService = publisherService;
        }

        // GET: Publishers
        public async Task<IActionResult> Index()
        {
            return View(await _publisherService.GetAll());
        }

        // GET: Publishers/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var publisher = await _publisherService.GetWithBooks(id);
            if (publisher == null)
            {
                return NotFound();
            }

            return View(publisher);
        }

        // GET: Publishers/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Publishers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Name")] Publisher publisher)
        {
            if (ModelState.IsValid)
            {
                await _publisherService.Insert(publisher);
                return RedirectToAction(nameof(Index));
            }
            return View(publisher);
        }

        // GET: Publishers/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var publisher = await _publisherService.Get(id);
            if (publisher == null)
            {
                return NotFound();
            }
            return View(publisher);
        }

        // POST: Publishers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Id")] Publisher publisher)
        {
            if (id != publisher.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _publisherService.Update(publisher);
                return RedirectToAction(nameof(Index));
            }
            return View(publisher);
        }

        // GET: Publishers/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var publisher = await _publisherService.Get(id);
            if (publisher == null)
            {
                return NotFound();
            }

            return View(publisher);
        }

        // POST: Publishers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _publisherService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

ELibrary.Web/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ELibrary.Domain.Models;
using ELibrary.Repository;
using ELibrary.Service.Interface;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;

namespace ELibrary.Web.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly IReviewService _reviewService;
        private readonly IBookService _bookService;
        private readonly IUserService _userService;

        public ReviewsController(IReviewService reviewService, IBookService bookService, IUserService userService)
        {
            _reviewService = reviewService;
            _bookService = bookService;
            _userService = userService;
        }

        // GET: Reviews/FromUser/5
        public async Task<IActionResult> FromUser(int? userid)
        {
            ViewData["MyReviews"] = false;
            if (!userid.HasValue)
            {
                userid = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
                ViewData["MyReviews"] = true;
            }
            IEnumerable<Review> reviews = await _reviewService.GetAllByUser(userid.Value);

            var user = await _userService.Get(userid.Value.ToString());

            ViewData["UserName"] = $"{user.Name} {user.Surname}";

            return View(reviews);
        }

        // GET: Reviews/Create/5
        public async Task<IActionResult> Create(int? bookid)
        {
            if (bookid == null)
            {
                return NotFound();
            }

            Book book = await _bookService.Get(bookid.Value);
            if (book == null)
            {
                return NotFound();
            }

            Review review = new Review(int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)), book.Id, 1, "");
            review.Book = book;

            ViewData["BookName"] = book.Name;
            return View(review);
        }

        // POST: Reviews/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,BookId,Rating,Comment")] Review review)
        {
            if (ModelState.IsValid)
            {
                await _reviewService.Insert(review);
                return RedirectToAction(nameof(FromUser));
            }
            return View(review);
        }

        // GET: Reviews/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Review review = await _reviewService.Get(id.Value);
            if (review == null)
            {
                return NotFound();
            }
            ViewData["BookName"] = (await _bookService.Get(review.BookId)).Name;
            return View(review);
        }

        // POST: Reviews/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,BookId,Rating,Comment,Id")] Review review)
        {
            if (id != review.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _reviewService.Update(review);
                return RedirectToAction(nameof(FromUser));
            }
            ViewData["BookName"] = (await _bookService.Get(review.BookId)).Name;
            return View(review);
        }

        // GET: Reviews/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Review review = await _reviewService.Get(id.Value);
            if (review == null)
            {
                return NotFound();
            }
            ViewData["BookName"] = (await _bookService.Get(review.BookId)).Name;
            return View(review);
        }

        // POST: Reviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _reviewService.Delete(id);
            return RedirectToAction(nameof(FromUser));
        }
    }
}

ELibrary.Web/Views/Books/Create.cshtml
@model ELibrary.Domain.Models.Book

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorId" class="control-label"></label>
                <select asp-for="AuthorId" class="form-control" asp-items="ViewBag.AuthorId"></select>
            </div>
            <div class="form-group">
                <label asp-for="CategoriesInBook" class="control-label"></label>
                <select asp-for="CategoriesInBook" id="CategoriesInBook" name="CategoriesInBook" size="4" multiple required>
                    @foreach (string cat in ELibrary.Domain.Models.Book.BookCategories)
                    {
                        <option value="@cat">@cat</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ELibrary.Web/Views/Books/Delete.cshtml
@model ELibrary.Domain.Models.Book

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Categories)
        </dt>
        <dd class="col-sm-10">
            @Model.Categories.Select(i => i.Category.Name).Aggregate((i, j) => i + ", " + j)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ImageLink)
        </dt>
        <dd class="col-sm-10">
            <img src="@Model.ImageLink" style="max-width: 300px;" />
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Authors)
        </dt>
        <dd class="col-sm-10">
            @foreach (BookAuthor ba in Model.Authors)
            {
                <a asp-controller="Authors" asp-action="Details" asp-route-id="@ba.AuthorId">@ba.Author.FullName()</a>
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Publisher)
        </dt>
        <dd class="col-sm-10">
            <a asp-controller="Publishers" asp-action="Details" asp-route-id="@Model.PublisherId">@Model.Publisher.Name</a>
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ELibrary.Web/Views/Books/Details.cshtml
@model ELibrary.Domain.Models.Book

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
<h4>@ViewData["BooksLeft"]</h4>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Categories)
        </dt>
        <dd class="col-sm-10">
            @Model.Categories.Select(i => i.Category.Name).Aggregate((i, j) => i + ", " + j)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ImageLink)
        </dt>
        <dd class="col-sm-10">
            <img src="@Model.ImageLink" style="max-width: 300px;" />
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Authors)
        </dt>
        <dd class="col-sm-10">
            @foreach (BookAuthor ba in Model.Authors)
            {
                <a asp-controller="Authors" asp-action="Details" asp-route-id="@ba.AuthorId">@ba.Author.FullName()</a><br />
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Publisher)
        </dt>
        <dd class="col-sm-10">
            <a asp-controller="Publishers" asp-action="Details" asp-route-id="@Model.PublisherId">@Model.Publisher.Name</a>
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AvgRating)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AvgRating) / 5
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TotalRents)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TotalRents)
        </dd>
    </dl>
</div>
<div>
    @if (User.IsInRole("Admin"))
    {
        <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Edit</a> <span>|</span>
    }
    @if ((bool)ViewData["Reviewable"] || User.IsInRole("Admin"))
    {
        <a asp-controller="Reviews" asp-action="Create" asp-route-bookid="@Model.Id" class="btn btn-light">Add Review</a> <span>|</span>
    }
    @if (User.Identity.IsAuthenticated)
    {
        <form asp-action="AddToCart" asp-route-id="@Model.Id">
            <input type="submit" value="Add To Cart" class="btn btn-primary" /> <span>|</span>
        </form>
    }
    <a asp-action="Index">Back to List</a>
</div>
<div>
    @foreach (Review review in Model.Reviews)
    {
        <hr />
        <div class="py-4">
            <h5>@($"{review.User.Name} {review.User.Surname}")</h5>
            <p style="color: dimgrey">Rating: @review.Rating / 5</p>
            <p>@review.Comment</p>
            @if (review.UserId == (int)ViewData["UserId"])
            {
                <a asp-controller="Reviews" asp-action="Edit" asp-route-id="@review.Id" method="get" class="btn btn-warning">Edit</a>
            }
            @if (review.UserId == (int)ViewData["UserId"] || User.IsInRole("Admin"))
            {
                <a asp-controller="Reviews" asp-action="Delete" asp-route-id="@review.Id" method="get" class="btn btn-danger">Delete</a>
            }
        </div>
    }
</div>

ELibrary.Web/Views/Books/Edit.cshtml
@model ELibrary.Domain.Models.Book

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageLink" class="control-label"></label>
                <input asp-for="ImageLink" class="form-control" />
                <span asp-validation-for="ImageLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Authors" class="control-label"></label>
                <select asp-for="Authors" id="CategoriesInBook" name="Authors" size="4" multiple required>
                    @foreach (Author author in ViewBag.authors)
                    {
                        if (Model.Authors.Select(i => i.AuthorId).Contains(author.Id))
                        {
                            <option value="@author.Id" selected>@author.FullName()</option>
                        }
                        else
                        {
                            <option value="@author.Id">@author.FullName()</option>
                        }
                    }
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Categories" class="control-label"></label>
                <select asp-for="Categories" id="CategoriesInBook" name="Categories" size="4" multiple required>
                    @foreach (Category category in ViewBag.categories)
                    {
                        if (Model.Categories.Select(i => i.CategoryId).Contains(category.Id))
                        {
                            <option value="@category.Id" selected>@category.Name</option>
                        }
                        else
                        {
                            <option value="@category.Id">@category.Name</option>
                        }
                    }
                </select>
            </div>
            <div class="form-group">
                <label asp-for="PublisherId" class="control-label"></label>
                <select asp-for="PublisherId" id="CategoriesInBook" name="PublisherId" required>
                    @foreach (Publisher publisher in ViewBag.publishers)
                    {
                        if (Model.PublisherId == publisher.Id)
                        {
                            <option value="@publisher.Id" selected>@publisher.Name</option>
                        }
                        else
                        {
                            <option value="@publisher.Id">@publisher.Name</option>
                        }
                    }
                </select>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ELibrary.Web/Views/Books/Index.cshtml
@model IEnumerable<ELibrary.Domain.Models.Book>

@{
    ViewData["Title"] = "Index";
}

<h1>Books</h1>

@if (User.IsInRole("Admin"))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}
<form asp-action="Index" method="get">
    <div class="col">
        <select name="categoryId" class="form-control">
            @if (ViewBag.chosenCategoryId == 0)
            {
                <option value="0" selected>All</option>
            }
            else
            {
                <option value="0">All</option>
            }
            @foreach (Category category in ViewBag.categories)
            {
                if (category.Id == ViewBag.chosenCategoryId)
                {
                    <option value="@category.Id" selected>@category.Name</option>
                }
                else
                {
                    <option value="@category.Id">@category.Name</option>
                }
            }
        </select>
    </div>
    <div class="col">
        <input type="submit" value="Search" class="btn btn-light" />
    </div>
</form>
<h4>@ViewData["BooksLeft"]</h4>
<div class="row">
    @foreach (Book book in Model)
    {
        <div class="col">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="@book.ImageLink" />
                <div class="card-body">
                    <h5 class="card-title">@book.Name</h5>
                    <p class="card-text">@string.Join(", ", book.Categories.Select(b => b.Category.Name))</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Average rating: @book.AvgRating.ToString("N2") / 5</li>
                    <li class="list-group-item">Total rents: @book.TotalRents.ToString()</li>
                </ul>
                <div class="card-body">
                    <a asp-action="Details" asp-route-id="@book.Id" class="btn btn-info">Details</a>
                    <form asp-action="AddToCart" asp-route-id="@book.Id">
                        <input type="submit" value="Add To Cart" class="btn btn-primary" />
                    </form>
                    @if (User.IsInRole("Admin"))
                    {
                        <a asp-action="Edit" asp-route-id="@book.Id" class="btn btn-warning">Edit</a>
                        <a asp-action="Delete" asp-route-id="@book.Id" class="btn btn-danger">Delete</a>
                    }
                </div>
            </div>
        </div>
    }
</div>
@if (User.IsInRole("Admin"))
{
    <form asp-action="Export" method="get">
        <div class="form-group">
            <label class="control-label">Category:</label>
            <select id="categoryId" name="categoryId">
                <option value="0" selected>All</option>
                @foreach (Category category in ViewBag.categories)
                {
                    <option value="@category.Id">@category.Name</option>
                }
            </select>
        </div>
        <div class="form-group">
            <input type="submit" value="Export books" class="btn btn-primary" />
        </div>
    </form>
}

ELibrary.Web/Views/Books/MoreDetails.cshtml
@model IDictionary<string, List<VDS.RDF.INode>>

@{
    ViewData["Title"] = "Details";
}

<h1>More Details - From DBPedia</h1>

<div>
    <h4><a href="@ViewData["subject"]">@ViewData["subject"]</a></h4>
    <hr />
    <dl class="row">
        @foreach (string key in Model.Keys)
        {
            <dt class="col-sm-2 my-2">
                <a href="@key">@key</a>
            </dt>
            <dd class="col-sm-10 my-2">
                @foreach (var node in Model[key])
                {
                    if (node.NodeType == VDS.RDF.NodeType.Uri)
                    {
                        <a href="@node.ToString()">@node.ToString()</a>
                    }
                    else
                    {
                        <span>@node.ToString()</span>
                    }
                    <br />
                }
            </dd>
        }
    </dl>
</div>
<div>
    <a asp-action="Details" asp-route-id="@ViewData["bookId"]">Back to Regular Details</a>
</div>